BIN := mtrx_op
SOURCES := matrix_operation.c task1.c task2.c task3.c task4.c 
HEADERS := mtrx_operation.h



CC := gcc

.PHONY := all clean

all: $(BIN)

$(BIN): 
		$(CC) $(SOURCES) -o $(BIN)	

$(BIN): $(HEADERS)

clean: 
		rm -rf $(BIN)